/*
 * Generated by tools/build_assets.py - do not edit by hand.
 * Embedded artwork: "PS5 Button Icons and Controls" by Zacksly
 * (https://zacksly.itch.io), licensed CC BY 3.0, modified.
 * SPDX-License-Identifier: GPL-3.0-or-later AND CC-BY-3.0
 */
#pragma once
#include <stdint.h>

typedef struct { const char *file; const uint8_t *data; uint32_t size; } pad_png_t;
typedef struct { const char *name; uint32_t bit; int16_t x, y, w, h; uint8_t png; } pad_sprite_t;
typedef struct { float cx, cy, travel; int16_t w, h; uint32_t click_bit; } pad_stick_t;
typedef struct { float x, y, w, h; int16_t dot_w, dot_h; } pad_touchpad_t;

enum {
    PAD_PNG_BASE,
    PAD_PNG_TRIANGLE,
    PAD_PNG_CIRCLE,
    PAD_PNG_CROSS,
    PAD_PNG_SQUARE,
    PAD_PNG_DPAD_UP,
    PAD_PNG_DPAD_DOWN,
    PAD_PNG_DPAD_LEFT,
    PAD_PNG_DPAD_RIGHT,
    PAD_PNG_L1,
    PAD_PNG_R1,
    PAD_PNG_CREATE,
    PAD_PNG_OPTIONS,
    PAD_PNG_MUTE,
    PAD_PNG_PS,
    PAD_PNG_TOUCHPAD,
    PAD_PNG_STICK_CAP,
    PAD_PNG_STICK_CAP_L3,
    PAD_PNG_L2_FILL,
    PAD_PNG_R2_FILL,
    PAD_PNG_TOUCH_DOT,
    PAD_PNG_COUNT
};

extern const int pad_overlay_w, pad_overlay_h;
extern const pad_png_t pad_pngs[PAD_PNG_COUNT];
extern const pad_sprite_t pad_buttons[15];
extern const pad_sprite_t pad_triggers[2];
extern const pad_stick_t pad_sticks[2];
extern const pad_touchpad_t pad_touchpad;
