/*
 * Generated by tools/build_perf_assets.py - do not edit by hand.
 * Copyright (C) 2026 erickdavestech
 * SPDX-License-Identifier: GPL-3.0-or-later
 */
#pragma once
#include <stdint.h>

typedef struct { const char *file; const uint8_t *data; uint32_t size; } perf_png_t;

enum {
    PERF_PNG_FRAME,
    PERF_PNG_RING_0,
    PERF_PNG_RING_1,
    PERF_PNG_RING_2,
    PERF_PNG_RING_3,
    PERF_PNG_RING_4,
    PERF_PNG_RING_5,
    PERF_PNG_RING_6,
    PERF_PNG_RING_7,
    PERF_PNG_RING_8,
    PERF_PNG_RING_9,
    PERF_PNG_RING_10,
    PERF_PNG_RING_11,
    PERF_PNG_RING_12,
    PERF_PNG_RING_13,
    PERF_PNG_RING_14,
    PERF_PNG_RING_15,
    PERF_PNG_RING_16,
    PERF_PNG_RING_17,
    PERF_PNG_RING_18,
    PERF_PNG_RING_19,
    PERF_PNG_RING_20,
    PERF_PNG_FAN_0,
    PERF_PNG_FAN_1,
    PERF_PNG_FAN_2,
    PERF_PNG_FAN_3,
    PERF_PNG_FAN_4,
    PERF_PNG_FAN_5,
    PERF_PNG_FAN_6,
    PERF_PNG_FAN_7,
    PERF_PNG_ICON_BOLT,
    PERF_PNG_ICON_THERMO,
    PERF_PNG_ICON_GAUGE,
    PERF_PNG_BAR,
    PERF_PNG_BAR_H,
    PERF_PNG_TRACK,
    PERF_PNG_COUNT
};

#define PERF_FAN_FRAMES 8
#define PERF_RING_FRAMES 21

extern const perf_png_t perf_pngs[PERF_PNG_COUNT];
